#pragma once

#define ORYX_CONFIGURATOR
#define RETRO_TAPPING

#define ERGODOX_WRAPPER
#define PERMISSIVE_HOLD

#undef RGBLIGHT_HUE_STEP
#define RGBLIGHT_HUE_STEP 1

#define DISABLE_RGB_MATRIX_DIGITAL_RAIN
#define DISABLE_RGB_MATRIX_ALPHAS_MODS
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_RAINDROPS
